import 'package:flutter_application_1/util/imports.dart';
import 'communities_post.dart';

List comm_post_list = [
  CommunitiesPost(
    postTitle: Text(
      '[Post Title]',
      style: TextStyle(fontSize: 16, fontWeight: FontWeight.w700),
    ),
    content: '[Content]',
    user: '[User]',
    timestamp: 'timestamp',
    category: '[Category]',
    gradient1: red,
    gradient2: orange,
    neonGlow: tran,
    shadowColor: white,
  ),
  CommunitiesPost(
    postTitle: Text(
      '[Post Title]',
      style: TextStyle(fontSize: 16, fontWeight: FontWeight.w700),
    ),
    content: '[Content]',
    user: '[User]',
    timestamp: 'timestamp',
    category: '[Category]',
    gradient1: red,
    gradient2: orange,
    neonGlow: tran,
    shadowColor: white,
  ),
  CommunitiesPost(
    postTitle: Text(
      '[Post Title]',
      style: TextStyle(fontSize: 16, fontWeight: FontWeight.w700),
    ),
    content: '[Content]',
    user: '[User]',
    timestamp: 'timestamp',
    category: '[Category]',
    gradient1: red,
    gradient2: orange,
    neonGlow: tran,
    shadowColor: white,
  ),
  CommunitiesPost(
    postTitle: Text(
      '[Post Title]',
      style: TextStyle(fontSize: 16, fontWeight: FontWeight.w700),
    ),
    content: '[Content]',
    user: '[User]',
    timestamp: 'timestamp',
    category: '[Category]',
    gradient1: red,
    gradient2: orange,
    neonGlow: tran,
    shadowColor: white,
  ),
  CommunitiesPost(
    postTitle: Text(
      '[Post Title]',
      style: TextStyle(fontSize: 16, fontWeight: FontWeight.w700),
    ),
    content: '[Content]',
    user: '[User]',
    timestamp: 'timestamp',
    category: '[Category]',
    gradient1: red,
    gradient2: orange,
    neonGlow: tran,
    shadowColor: white,
  ),
  CommunitiesPost(
    postTitle: Text(
      '[Post Title]',
      style: TextStyle(fontSize: 16, fontWeight: FontWeight.w700),
    ),
    content: '[Content]',
    user: '[User]',
    timestamp: 'timestamp',
    category: '[Category]',
    gradient1: red,
    gradient2: orange,
    neonGlow: tran,
    shadowColor: white,
  ),
  CommunitiesPost(
    postTitle: Text(
      '[Post Title]',
      style: TextStyle(fontSize: 16, fontWeight: FontWeight.w700),
    ),
    content: '[Content]',
    user: '[User]',
    timestamp: 'timestamp',
    category: '[Category]',
    gradient1: red,
    gradient2: orange,
    neonGlow: tran,
    shadowColor: white,
  ),
  CommunitiesPost(
    postTitle: Text(
      '[Post Title]',
      style: TextStyle(fontSize: 16, fontWeight: FontWeight.w700),
    ),
    content: '[Content]',
    user: '[User]',
    timestamp: 'timestamp',
    category: '[Category]',
    gradient1: red,
    gradient2: orange,
    neonGlow: tran,
    shadowColor: white,
  ),
  CommunitiesPost(
    postTitle: Text(
      '[Post Title]',
      style: TextStyle(fontSize: 16, fontWeight: FontWeight.w700),
    ),
    content: '[Content]',
    user: '[User]',
    timestamp: 'timestamp',
    category: '[Category]',
    gradient1: red,
    gradient2: orange,
    neonGlow: tran,
    shadowColor: white,
  ),
  CommunitiesPost(
    postTitle: Text(
      '[Post Title]',
      style: TextStyle(fontSize: 16, fontWeight: FontWeight.w700),
    ),
    content: '[Content]',
    user: '[User]',
    timestamp: 'timestamp',
    category: '[Category]',
    gradient1: red,
    gradient2: orange,
    neonGlow: tran,
    shadowColor: white,
  ),
  CommunitiesPost(
    postTitle: Text(
      '[Post Title]',
      style: TextStyle(fontSize: 16, fontWeight: FontWeight.w700),
    ),
    content: '[Content]',
    user: '[User]',
    timestamp: 'timestamp',
    category: '[Category]',
    gradient1: red,
    gradient2: orange,
    neonGlow: tran,
    shadowColor: white,
  ),
  CommunitiesPost(
    postTitle: Text(
      '[Post Title]',
      style: TextStyle(fontSize: 16, fontWeight: FontWeight.w700),
    ),
    content: '[Content]',
    user: '[User]',
    timestamp: 'timestamp',
    category: '[Category]',
    gradient1: red,
    gradient2: orange,
    neonGlow: tran,
    shadowColor: white,
  ),
  CommunitiesPost(
    postTitle: Text(
      '[Post Title]',
      style: TextStyle(fontSize: 16, fontWeight: FontWeight.w700),
    ),
    content: '[Content]',
    user: '[User]',
    timestamp: 'timestamp',
    category: '[Category]',
    gradient1: red,
    gradient2: orange,
    neonGlow: tran,
    shadowColor: white,
  ),
  CommunitiesPost(
    postTitle: Text(
      '[Post Title]',
      style: TextStyle(fontSize: 16, fontWeight: FontWeight.w700),
    ),
    content: '[Content]',
    user: '[User]',
    timestamp: 'timestamp',
    category: '[Category]',
    gradient1: red,
    gradient2: orange,
    neonGlow: tran,
    shadowColor: white,
  ),
  CommunitiesPost(
    postTitle: Text(
      '[Post Title]',
      style: TextStyle(fontSize: 16, fontWeight: FontWeight.w700),
    ),
    content: '[Content]',
    user: '[User]',
    timestamp: 'timestamp',
    category: '[Category]',
    gradient1: red,
    gradient2: orange,
    neonGlow: tran,
    shadowColor: white,
  ),
  CommunitiesPost(
    postTitle: Text(
      '[Post Title]',
      style: TextStyle(fontSize: 16, fontWeight: FontWeight.w700),
    ),
    content: '[Content]',
    user: '[User]',
    timestamp: 'timestamp',
    category: '[Category]',
    gradient1: red,
    gradient2: orange,
    neonGlow: tran,
    shadowColor: white,
  ),
  CommunitiesPost(
    postTitle: Text(
      '[Post Title]',
      style: TextStyle(fontSize: 16, fontWeight: FontWeight.w700),
    ),
    content: '[Content]',
    user: '[User]',
    timestamp: 'timestamp',
    category: '[Category]',
    gradient1: red,
    gradient2: orange,
    neonGlow: tran,
    shadowColor: white,
  ),
  CommunitiesPost(
    postTitle: Text(
      '[Post Title]',
      style: TextStyle(fontSize: 16, fontWeight: FontWeight.w700),
    ),
    content: '[Content]',
    user: '[User]',
    timestamp: 'timestamp',
    category: '[Category]',
    gradient1: red,
    gradient2: orange,
    neonGlow: tran,
    shadowColor: white,
  ),
  CommunitiesPost(
    postTitle: Text(
      '[Post Title]',
      style: TextStyle(fontSize: 16, fontWeight: FontWeight.w700),
    ),
    content: '[Content]',
    user: '[User]',
    timestamp: 'timestamp',
    category: '[Category]',
    gradient1: red,
    gradient2: orange,
    neonGlow: tran,
    shadowColor: white,
  ),
  CommunitiesPost(
    postTitle: Text(
      '[Post Title]',
      style: TextStyle(fontSize: 16, fontWeight: FontWeight.w700),
    ),
    content: '[Content]',
    user: '[User]',
    timestamp: 'timestamp',
    category: '[Category]',
    gradient1: red,
    gradient2: orange,
    neonGlow: tran,
    shadowColor: white,
  ),
  CommunitiesPost(
    postTitle: Text(
      '[Post Title]',
      style: TextStyle(fontSize: 16, fontWeight: FontWeight.w700),
    ),
    content: '[Content]',
    user: '[User]',
    timestamp: 'timestamp',
    category: '[Category]',
    gradient1: red,
    gradient2: orange,
    neonGlow: tran,
    shadowColor: white,
  ),
  CommunitiesPost(
    postTitle: Text(
      '[Post Title]',
      style: TextStyle(fontSize: 16, fontWeight: FontWeight.w700),
    ),
    content: '[Content]',
    user: '[User]',
    timestamp: 'timestamp',
    category: '[Category]',
    gradient1: red,
    gradient2: orange,
    neonGlow: tran,
    shadowColor: white,
  ),
  CommunitiesPost(
    postTitle: Text(
      '[Post Title]',
      style: TextStyle(fontSize: 16, fontWeight: FontWeight.w700),
    ),
    content: '[Content]',
    user: '[User]',
    timestamp: 'timestamp',
    category: '[Category]',
    gradient1: red,
    gradient2: orange,
    neonGlow: tran,
    shadowColor: white,
  ),
  CommunitiesPost(
    postTitle: Text(
      '[Post Title]',
      style: TextStyle(fontSize: 16, fontWeight: FontWeight.w700),
    ),
    content: '[Content]',
    user: '[User]',
    timestamp: 'timestamp',
    category: '[Category]',
    gradient1: red,
    gradient2: orange,
    neonGlow: tran,
    shadowColor: white,
  ),
  CommunitiesPost(
    postTitle: Text(
      '[Post Title]',
      style: TextStyle(fontSize: 16, fontWeight: FontWeight.w700),
    ),
    content: '[Content]',
    user: '[User]',
    timestamp: 'timestamp',
    category: '[Category]',
    gradient1: red,
    gradient2: orange,
    neonGlow: tran,
    shadowColor: white,
  ),
  CommunitiesPost(
    postTitle: Text(
      '[Post Title]',
      style: TextStyle(fontSize: 16, fontWeight: FontWeight.w700),
    ),
    content: '[Content]',
    user: '[User]',
    timestamp: 'timestamp',
    category: '[Category]',
    gradient1: red,
    gradient2: orange,
    neonGlow: tran,
    shadowColor: white,
  ),
  CommunitiesPost(
    postTitle: Text(
      '[Post Title]',
      style: TextStyle(fontSize: 16, fontWeight: FontWeight.w700),
    ),
    content: '[Content]',
    user: '[User]',
    timestamp: 'timestamp',
    category: '[Category]',
    gradient1: red,
    gradient2: orange,
    neonGlow: tran,
    shadowColor: white,
  ),
  CommunitiesPost(
    postTitle: Text(
      '[Post Title]',
      style: TextStyle(fontSize: 16, fontWeight: FontWeight.w700),
    ),
    content: '[Content]',
    user: '[User]',
    timestamp: 'timestamp',
    category: '[Category]',
    gradient1: red,
    gradient2: orange,
    neonGlow: tran,
    shadowColor: white,
  ),
];
